### PR TITLE
Update asciidoctorj to 1.5.8.1

### PR DESCRIPTION
**Pull request by abelsromero**
This updates AsciidoctorJ version and tests that started failing due to https://github.com/asciidoctor/asciidoctor/issues/2722.

@mojavelinux I added about the issue in the README. I'd appreciate your opinion on wether we should make this visible or not.

### CODE REVIEW

**Comment by mojavelinux** [comment]
In my opinion, this should have never been enabled because it wasn't a complete feature. So we can mention it, but it's just consistent with the behavior of the Asciidoctor API now.

**Comment by mojavelinux** [comment]
Btw, I think you can reenable this behavior by creating a script with the following contents:

```rb
$VERBOSE=true
```

Then requiring that script in the plugin configuration. That emulates the Asciidoctor API exactly.

**Comment by abelsromero** [comment]
> Btw, I think you can reenable this behavior by creating a script with the following contents:

But then we may leak excessive information. I am more inclined to adding a <verbose> option and letting people choose.

**Comment by mojavelinux** [comment]
> But then we may leak excessive information.

What I'm trying to say is that's the only way it worked before. This was never a warning that got passed through the logger under normal circumstances. So there's no loss of feature here. It works as it always has. (It just has to be enabled differently). Any change to have a proper warning is an enhancement for a future release.

**Comment by abelsromero** [comment]
> It works as it always has. (It just has to be enabled differently).

Thanks for the clarification.
To avoid any impact on someone that may have been using this, even it was not intended, I will see if I can add `<enableVerbose>` option in another PR.

**Comment by mojavelinux** [comment]
>  I will see if I can add <enableVerbose> option in this PR.

Sounds like a good idea.

**Comment by abelsromero** [comment]
I must admit, it's been much, much easier than expected. The verbose script works fine even when setting and additional gempath, and when running from inside the plugin's jar.

I changed the warning to note and explained in a more positive way.

**Pull request merged**
