### PR TITLE
Upgrade to AsciidoctorJ 2.0.0-RC.1

### PR DESCRIPTION
**Pull request by robertpanzer**
This PR makes the required changes to upgrade the plugin to AsciidoctorJ 2.0.0-RC.1

Notable changes are:
* Minimum required version of Java is now Java 8
* I ignored the tests for the warnings for invalid refs, I also have them commented in AsciidoctorJ

There's one test failing locally for me right now, which expects rendering with the Pygments highlighter to fail, however that succeeds.
I am unclear right now if this is now the expected behavior or if this is coming from my local machine setup, even though I don't have pygments installed locally afaict.

### CODE REVIEW

**Comment by abelsromero** [comment]
> There's one test failing locally for me right now, which expects rendering with the Pygments highlighter to fail, however that succeeds.
> I am unclear right now if this is now the expected behavior or if this is coming from my local machine setup, even though I don't have pygments installed locally afaict.

It was there as a reminder of an Asciidoctor bug, if it's fixed, we can update the test. I'll have a look at it.

One thing I had in my bucket list was the jruby dependency. Should we change to `org.jruby:jruby` instead of `jruby-complete`?

**Comment by robertpanzer** [comment]
> One thing I had in my bucket list was the jruby dependency. Should we change to org.jruby:jruby instead of jruby-complete?

Good idea, I'll update the PR

**Comment by abelsromero** [comment]
> Good idea, I'll update the PR

You have some time.
To be honest wanted to do a last release ensuring compatibility with 1.5.8.1 & 1.6.2 before working on 2.0.0. I am counting everything should work and it would not take much time tomorrow.
I'll write an issue with the 2.0.0 plan asap

**Comment by robertpanzer** [comment]
That's also a great idea :D 
I just had some spare time so could do a quick PR for this.
I don't mind if it will take more time to review, that's all good.

**Comment by abelsromero** [comment]
I already added the fix for the remote include test in master and confirmed the pygments issue is fixed in 2.x, but not before.

**Comment by abelsromero** [comment]
I am merging, even when some test may be failing, I'll fix them right now.

**Comment by abelsromero** [comment]
I checked the test that now passes with `pygments` and it seems that the previous error message `Pygments is not available` is not returned and the HTML is generated adding `pygments` css class to HTML code element. But not style is applied, not sure what I missing since I haver python2 installed and I could correctly convert the doc (with stylng) with the ruby cli after installing `pygments.rb` gem. Could it be we need to add pygments to AsciidoctorJ jar?
@robertpanzer do you think it makes sense to treat it in AsciidoctorJ.

Right now I am setting the test to Ignore until I have more time.

**Comment by abelsromero** [comment]
>     * I ignored the tests for the warnings for invalid refs, I also have them commented in AsciidoctorJ

I hate sounding like a manager, but honestly, "I understand this is a known issue and is being worked on?"

**Comment by robertpanzer** [comment]
I just remembered. 
It’s no longer ties to the -verbose flag. 
Instead it’s necessary to set the global variable `$VERBOSE` in an extension to get the warnings for invalid refs. 
I can add such an extension and enable the test again tomorrow.

**Comment by robertpanzer** [comment]
For reference: https://github.com/asciidoctor/asciidoctorj/pull/689

**Comment by abelsromero** [comment]
> I can add such an extension and enable the test again tomorrow.

Don't worry. In fact let it to me, so I can play with it and document it better in the readme.

**Comment by abelsromero** [comment]
Surprise, it's already done https://github.com/asciidoctor/asciidoctor-maven-plugin/pull/384 I just forgot.
I'll check why it is not working

**Comment by mojavelinux** [comment]
I know the changes in core caused a bit of confusion about when invalid references are logged. To clarify, as of 2.0, they get logged when the logger threshold is INFO or DEBUG. See https://github.com/asciidoctor/asciidoctor/blob/master/lib/asciidoctor/substitutors.rb#L776

**Comment by mojavelinux** [comment]
In other words, we no longer use the $VERBOSE global for this. That's now reserved for runtime warnings, such as an unused variable (which is the normal way of using it).

**Comment by robertpanzer** [comment]
I think I see what's going on.
Asciidoctor now checks the log level before logging. 
I have to implement the explicit methods for info, warn etc.
I think previously Logger.add was called.

**Comment by abelsromero** [comment]
If I understand correctly is a thing for AsciidoctorJ then. Please, refer the PR or issue to track it.

**Pull request merged**
