### PR TITLE
remove antora stuff for standalone deployed docs site

### LINKED ISSUE #529: missing start page for standalone documentation site
Thank you for taking your time to talk with us!

**What is this issue about?**

- [x] Bug report
- [ ] Feature request
- [ ] Question

**Description**
I checked the deployments for gh-pages and this don't worked. I think the start pages is missing.

### PR DESCRIPTION
**Pull request by uniqueck**
Thank you for opening a pull request and contributing to asciidoctor-maven-plugin!

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [ ] Feature
- [x] Documentation
- [ ] Refactor
- [ ] Build improvement
- [ ] Other (please describe)

**What is the goal of this pull request?**
This pull request fixes #529 and correct start page for standalone documentation site on gh-pages.

**Are there any alternative ways to implement this?**
no

**Are there any implications of this pull request? Anything a user must know?**
no

**Is it related to an existing issue?**
 
- [x] Yes
- [ ] No

*Finally, please add a corresponding entry to CHANGELOG.adoc*

### CODE REVIEW

**Comment by abelsromero** [comment]
Thanks for the notice! To tell the truth, the ghpages antora site was a temporal thing while setting up the final docs (https://docs.asciidoctor.org) and forgot about it. What we should probably do is remove it from our repo since the playbok is in https://github.com/asciidoctor/docs.asciidoctor.org. Including the gh-action and README link. When done I can disable the gh-pages branch.

Do you want to take on it?


PS: `start_page` points by default to ROOT:index.adoc iirc, at leas in https://docs.asciidoctor.org/maven-tools/latest/ seems to work fine.

**Comment by uniqueck** [comment]
Ok i can do it. I will cleanup all unnecessary stuff for this local gh-pages based on antora.

**Comment by uniqueck** [comment]
Hi @abelsromero, please have a look for this updated PR.

**Comment by abelsromero** [comment]
Iirc there are some links int he readme?

**Comment by uniqueck** [comment]
Oh a good hint, i check this.

**Comment by abelsromero** [comment]
I think updating the `:uri-docs:` attribute should be enough.

**Comment by uniqueck** [comment]
Sorry for the delay, yesterday was no time. Thanks for the point with docs-uri.

**Comment by abelsromero** [comment]
> Sorry for the delay, yesterday was no time. Thanks for the point with docs-uri.

Sorry, I has some time and was reviewing thing, it was more a note to self than a push 😅

**Comment by abelsromero** [comment]
Excellentm, thanks a lot!

**Pull request merged**
