### PR TITLE
269 Exclude docinfo files by default

### PR DESCRIPTION
**Pull request by ge0ffrey**
Fixes https://github.com/asciidoctor/asciidoctor-maven-plugin/issues/269

### CODE REVIEW

**Comment by abelsromero** [comment]
Just one thing, could you add some test?
I know in this case it's not 100% necessary, but it helps a lot in the future to ensure behavior stays consistent if we change something.

**Comment by ge0ffrey** [comment]
Got a pointer to a test I can copy-paste-adjust?

**Comment by abelsromero** [comment]
Sure!
You can use this method https://github.com/ge0ffrey/asciidoctor-maven-plugin/blob/master/src/test/groovy/org/asciidoctor/maven/test/AsciidoctorMojoTest.groovy#L32-L59

You'll need to:
- remove the resources filter
- add the attribute configuration, IIRC `mojo.attributes['docinfo1']= 'true'`
- add a docInfo.html file to the src/test/resources directory
- validate that the file is not found in the target and that the content is added to the text. The test has examples about that.

Also, to ensure (to some degree) tests isolation, you can add some timestamp to the output like this `File outputDir = new File("target/asciidoctor-output/${System.currentTimeMillis()}")`

**Comment by mojavelinux** [comment]
Should we exclude all docinfo file extensions as well? In other words, when converting to DocBook, is the plugin currently copying the .xml files?

**Comment by abelsromero** [comment]
The PR shows the only filters that are currently applied (_ prefix). So docinfo XML files are copied.
The thing is that if we want to be 100% accurate we should filter only the appropriate files based on the backend and docinfo attribute (docinfo, docinfo1 and docinfo3), and even take into consideration the `<docname>`. Is not hard, but requires some work.
I am basing my assumptions on these: 
http://asciidoctor.org/docs/user-manual/#docinfo-attributes-and-file-names and
http://asciidoctor.org/docs/user-manual/#footer-docinfo-files, we need additional logic.

**Comment by mojavelinux** [comment]
While you are indeed correct, I personally feel like that would be overkill. The term "docinfo" in general should be considered reserved and files that include it (particularly with the patters we've put forth) should not expected to be copied. I'm not opposed to a more fine-grained approach...I'm just saying it isn't strictly necessary.

**Comment by ge0ffrey** [comment]
I agree that taking backend and docinfo into account would be better, but imo it shouldn't prevent merging this PR as is. The lack of a test is indeed a problem, I 'll update the pr with a test tomorrow.

Any plans to do a release of this plugin?

**Comment by abelsromero** [comment]
> While you are indeed correct, I personally feel like that would be overkill.

I am glad we all agree on that. So filtering all options (html and xml) should be enough.


> Any plans to do a release of this plugin?

@ge0ffrey, about the release, there are a couple PR that would be nice to include but they aren't mandatory. The only blocking thing for me is the release of AsciidoctorJ 1.5.4.2 which includes a patch to fix an issue with extension https://github.com/asciidoctor/asciidoctor-maven-plugin/pull/258. Without it, some plugin tests fail.

**Comment by ge0ffrey** [comment]
PR updated with unit test and exclusion of docinfo.xml variants. Should be ready to merge, do note that this is my first Groovy unit test :)

**Comment by abelsromero** [comment]
> do note that this is my first Groovy unit test :)

I have no changes to propose. It can surely be optimized, but as for me, I prefer readability in tests over fancy one-liners.

I'll leave it open while we wait to see about the AsciidoctorJ release (https://github.com/asciidoctor/asciidoctorj/pull/498), just in case someone else wants to add anything.

**Comment by ge0ffrey** [comment]
Thanks :)

**Comment by abelsromero** [comment]
Thanks to you. As a general note, if you see I don't answer/merge in a couple of days, feel free to ping me on the thread or twitter.

**Pull request merged**
