### PR TITLE
improved explanations on Maven Plugin vs Maven Site Integration/Doxia

### PR DESCRIPTION
**Pull request by hboutemy**

### CODE REVIEW

**Comment by abelsromero** [comment]
I added a couple of notes for simplification and avoiding repetition.

**Comment by hboutemy** [comment]
great! but I don't see where you put these notes
Don't hesitate to improve content when merging

**Comment by abelsromero** [comment]
I am still familiar with the new review model, seems I need to confirm my comments to make them visible. Should be visible now.

**Comment by abelsromero** [comment]
Just checking @hboutemy can you see the comments now?

**Comment by hboutemy** [comment]
sorry, I was busy on other tasks
improvements done, and more: now, each scenario has one "Setup" and one "Configuration" sections
this is a lot better IMHO: thank you for the feedback

**Comment by abelsromero** [comment]
> each scenario has one "Setup" and one "Configuration" sections

I have to say that I really like it.
Being non english native I use setup and config indistinctly, but I checked the dictionay and it fits.

I'll leave it open 24h in case someone else wants to say something, but it's fine for me.

**Comment by hboutemy** [comment]
I like the result too: good team work :)

**Pull request merged**
