### PR TITLE
Mark BuildMojo as threadSafe

### PR DESCRIPTION
**Pull request by timkrueger**
This annotation will remove a maven build warning.

Resolves: #326

### CODE REVIEW

**Comment by abelsromero** [comment]
We could try a `it` test with a couple of submodules with differnet documents.
If the documents don't mix content, we can assume it's OK (here there's an example https://github.com/abelsromero/asciidoctor-maven-plugin/tree/add_capture_of_Asciidoctor_log_messages/src/it/spi-registered-log).
Reviewing Maven documentation & code again, I don't see why it should fail un multi-thread scenario.

**Comment by timkrueger** [comment]
I think now I got it 😁

**Comment by abelsromero** [comment]
I guess that should be enough 👍

**Comment by timkrueger** [comment]
@abelsromero Any plans when 1.5.7 will be released?

**Comment by abelsromero** [comment]
Only pending thing is https://github.com/asciidoctor/asciidoctor-maven-plugin/pull/363. Since is a long requested feature I'd really appreciate some feedback :% but I'd probably merge this weekend regardless.

**Pull request merged**
