### PR TITLE
Update README.adoc

### PR DESCRIPTION
**Pull request by matdere**
Following @mojavelinux  suggestion on the bug #156 : my little contribution to the project. Thanks again.

### CODE REVIEW

**Comment by abelsromero** [comment]
Nice addition :) But I have a doubt, shouldn't `numbered` be in an `attributes` block? I can't test it right now. If that's the case, adding some extra information on how boolean properties are handled would be helpfull. There's already a small note in the README, but some more detail on the equivance of <numbered> with </numbered> would avoid confusions.
wdyt?

**Comment by matdere** [comment]
@abelsromero you're right numbered should be an attibutes block. I did the modification and added an example to the boolean handling part also.

**Comment by mojavelinux** [comment]
@matdere @abelsromero Even better would be to use the new name in 1.5.x for `numbered`, which is `sectnums`. This makes it more clear what is being numbered since it only applies to section numbers. If you can update, then otherwise the change looks great to me. Thanks for contributing it!

**Comment by abelsromero** [comment]
Just out of curiosity, because I know you (Dan) are a very thoughtful person and I see you already corrected the user manual (https://github.com/asciidoctor/asciidoctor.org/commit/5457ae2f4e6ebbf65e7a66dd4ef4e47adba1cd43)

Is the attribute here mantained for some reason?
https://raw.githubusercontent.com/asciidoctor/asciidoctor.org/master/docs/_includes/ex-appendix.adoc

**Comment by mojavelinux** [comment]
Thanks for pointing that out, @abelsromero. I probably just missed it. I was mostly focused on updating the main mention of it and I caught it a few other places. We need to keep going to weed all mentions out except the admonition note that says we still support `numbered` for backward compatibility.

**Pull request merged**
