### PR TITLE
Remove dependency to oss-parent and copy to local pom.xml

### PR DESCRIPTION
**Pull request by slachiewicz**
First - remove only parent-pom.
Next, i will add selected plugin updates from #337 

cc: @khmarbaise could You help with validation?

### CODE REVIEW

**Comment by abelsromero** [comment]
Looked into [this](https://maven.apache.org/guides/mini/guide-central-repository-upload.html) and I think we can totally remove the parent. After all we are publishing through jcenter.

**Comment by slachiewicz** [comment]
Yes, we can remove parent-pom, but we should include all that was defined here. 
I try to compare effective pom (_mvn help:effective-pom_) before, and after patch and looks equal.
Later you can remove a reduntant entries

**Comment by abelsromero** [comment]
> Yes, we can remove parent-pom, but we should include all that was defined here.

I totally agree with that to be safe. But I think we can go a bit further ;)

The oss-parent `maven-release-plugin` adds the `sonatype-oss-release` profile which overwrites `source`, `javadoc` and `gpg` plugins. But those are already defined, and honestly the options the oss build sets seem to be outdated to me.

I am ok with going ahead and seeing if we can simplify later. But wdyt, do we take our change now?

**Comment by mojavelinux** [comment]
I'm completely in support of this change. There was a time when that parent made sense. That time has passed. So this is really just residue from an old setup.

**Comment by slachiewicz** [comment]
Ok, i've removed redundant sonatype-oss-release profile and snapshot repository. 
It was good for me to check how deployment to jcenter works - thx :) 
After squash - I think all should be ready now for merge.

**Pull request merged**
