### PR TITLE
Invoke JavaExtensionRegistry by reflection to take care of binary inc…

### PR DESCRIPTION
**Pull request by robertpanzer**
…ompatibilities with AsciidoctorJ 1.6.0

Related to asciidoctor/asciidoctorj#491

To also support AsciidoctorJ 1.6.0 it will be necessary to invoke JavaExtensionsRegistry via Reflection.

### CODE REVIEW

**Comment by abelsromero** [comment]
:+1:

**Comment by mojavelinux** [comment]
Nice work!

I think we should mark that this should be changed back to a regular invocation once we move to 1.6.x version of the plugin. Version 1.6.x of the plugin will require version 1.6.x of AsciidoctorJ...and thus we will be back in binary alignment. wdyt?

**Comment by robertpanzer** [comment]
Like this? :-)
https://github.com/asciidoctor/asciidoctor-maven-plugin/pull/255/files#diff-3c89526d74c66dc30084df700cd6c102R55

**Comment by mojavelinux** [comment]
:+1:

**Pull request merged**
